from .age.grab import grabAge
from .gender.grab import grabGender
from .income.grab import grabIncome
from .job.grab import grabJob
from .name.grab import grabName
from .race.grab import grabRace
from .shelter.grab import grabShelter
from .transportation.grab import grabTransportation
from .personality.grab import grabPersonality
